### ISSUE TITLE
Rock Deployments

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Rock#23]
**So you want to deploy Rock you say....**

We currently support three remote environments for the Rock application. We have a development owned alpha environment, a co-owned beta environment, and an IT owned production environment. Each environment is controlled and deployed via the corresponding branches in this repository. This repo also handles upstream merges and from SparkNetwork.

**Okay thats cool and all, but how to do I deploy?**

Simply! Whenever a commit is pushed (or merged) to any of the following branches: master, beta, alpha,  an automated build will be triggered using the Appveyor CI service. Once this build is done, if it is successful, a build will be staged for deployment. If the alpha branch is what you are working on, it will automatically get deployed to alpha-rock.newspring.cc and run any corresponding migrations. If you intended to deploy to beta or master, the build will be staged and IT alerted as they make the call to deploy to those environments.

**That's pretty cool, how do I write code for this sweet project?**

Also pretty easy! You will need Visual Studio and node + Norma installed. If you clone down this repo and run `Norma build`, it will pull in all of the needed projects. Then you can run the build in Visual Studio and off you go!

**Wait, I want to work on a plugin / theme**

Okay thats no problem! After pulling the project down, you can symlink your local version of a project (say rock-workflows) to the .\.remote\workflows folder. Then if you run `norma` while you are working on the project (from the Rock project), any changes you make will be updated and synced to where they need to run. Then you can commit from your local copy of the remote plugin / theme happily.

**How do I test my plugin in an environment?**

Right now, each Rock branch will pull from its corresponding plugin branches (e.g. beta branch of Rock pulls from beta branches of plugins). Stage your plugin to its corresponding environment branch, then it will trigger a deploy of Rock from that same branch. For example, rock-apollos@alpha deploys rock@alpha which pulls in the alpha of all plugins.

**This is cool, what about updating Rock Core?**

This is pretty easy as well! We **ONLY** use the pre-release-alpha branch from Rock right now. Eventually production will pull from the latest stable release instead. To pull from Rock, first add the core repo to your upstream of your clone `git remote add upstream https://github.com/SparkDevNetwork/Rock.git`. Then when you want to merge, `git fetch upstream && git merge upstream/pre-alpha-release`. This will bring the latest from core into our fork. In the future this will be automated as well. Then just push and your branch will have the latest from core.

**I want to make something new!**

So cool! Can't wait to see what it is! To start, checkout the master branch of this project and pull to make sure you have the latest. Then `git checkout -b feature-<my-thing>`. At this point you have a branch ready to work on that is up to date with the latest from master. Then you can PR your branch through the environments all the way to production. Huzzah!

**I have more questions**

Submit an issue here! We will do our best to lend a hand and get it sorted out!

**Comment by alexdresko** [comment]
@jbaxleyiii Does `norma build` still work? 

![image](https://cloud.githubusercontent.com/assets/333022/17117399/ea4c19dc-5289-11e6-9f1c-909ef9dfb648.png)

![image](https://cloud.githubusercontent.com/assets/333022/17117408/f31e1678-5289-11e6-85d4-fe08c5b855b6.png)

**Comment by alexdresko** [comment]
nvm... I think I just need to clone all of those projects.

**Comment by dcs619** [comment]
Visual Studio doesn't depend on the plugin projects being cloned down, but
Norma might.  What are you trying to do?

David Stevens

*Web Developer*NewSpring Church
www.newspring.cc

**Comment by alexdresko** [comment]
Hi @dcs619 ... long time.. 

I cloned this repo and am trying to get it to build.. have some ideas.. Don't really know if I'm headed in the right direction though. Just figured this would be a good start. At this point, I have all of the projects loaded except for RockWeb.. can't seem to find that one.

**Comment by alexdresko** [comment]
I totally rushed into this, I know... currently watching https://www.rockrms.com/page/513?Item=67 so thinking probably that'll help. Reading the docs at the same time. 

I'm in rapid absorption mode.
