### ISSUE TITLE
Dynamic Rock config vars

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Rock#26]
@jbaxleyiii Do you know if it's possible to set the Rock config vars dynamically, similar to how we run the EE master config? That way we could auto set the URL + internal paths automatically per server we deploy on.

https://www.dropbox.com/s/9m4n8nb7w0cljd1/Screenshot%202015-10-18%2015.18.25.png?dl=0

**Comment by jbaxleyiii** [comment]
@jonhorton I'm not sure if it is currently possible to do that (I admittedly don't know the structure of the project well enough). I do think it would be great to do that however! Worth reaching out to the core team for sure. If they can point me in the right direction, I'm sure I could whip something together
