### ISSUE TITLE
DRAFT: [EN] Content Channel Relationship Field Type

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Rock#307]
_**Once we’ve got this polished, we’ll publish it to the Spark repo.**_

After spending a few weeks building a site from the ground up and integrating it into Rock's CMS, it doesn't appear that there is currently a way to create relationships between content channel items. As we look toward using the CMS functionality of Rock in the future at NewSpring, this is one key function that we believe is a must, not just for us, but for many others as well.

At its core, a relationship fieldtype exists as a flexible dropdown – the options of which are populated by entries from another content channel. The simplest example I can give would be **creating relationships between sermon series & sermon entries.** For instance, we'd need a way to relate a `WeeklySermons` channel entry to the `SermonSeries` entry that that sermon is a part of.   Expanding on that, we'd also need a way to relate entries from a `Devotionals` channel to the `SermonSeries` channel, or a `GroupStudies` channel entry to the current series.

Beyond the field itself, we'd like to be able to pull data sideways from related entries in lava. I'm not super familiar with Rock's data structure, so this is a basic idea of how that could work: 

```
<!-- Lava within Content Channel View Block (Series Channel) -->
{% for seriesItem in SermonSeries %}
    <h2>{{ seriesItem.Title }}</h2>
    <ul>
        {% for sermon in seriesItem.WeeklySermons %}
            <li>{{ sermon.Title }}</li>
        {% endfor %}
    </ul>
{% endfor %}
```

Beyond the basic functionality of creating relationships and accessing attributes across them, some options for filtering the selectable entries would be incredibly helpful as well.
- Allow Multiple Selections (Relate an entry to multiple entries)
- Filter by Channel (Can be entries from a single or multiple channels)
- Filter by Default/Custom Attribute(s)
- Filter by Author
- Filter by Date
- Filter by Status
- Order Entries by Item Attribute + Sort Asc/Desc

We just wanted to put this out there to start a dialogue about the need for something like this and how we could go about putting together a solution. **Any and all suggestions welcome!**

**Comment by briankalwat** [comment]
**Once we’ve got it polished, we’ll publish it to the Spark repo.**

**Comment by richarddubay** [comment]
![giphy](https://cloud.githubusercontent.com/assets/3229463/16021302/e4e57734-317f-11e6-9ba4-09630c4b5c2e.gif)
