### ISSUE TITLE
Slow AD Logins for Rock

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock#326]
Known issue, reported by @briankalwat again during Gauntlet.
- [x] Suggestions to check ports 389, 636 on DC
- [ ] Adjust [NetBIOS / WINS / Hosts](http://stackoverflow.com/a/5052658/1853867) file
- [ ] Switch auth to [use an LDAP provider](http://stackoverflow.com/a/10938574/1853867).  This might also enable us to use Xamarin to build Rock.
- [ ] Check DC controller logs `%systemroot%\netlogon\`
- [ ] Verify [PrincipalContext](http://stackoverflow.com/q/4469795/1853867) is being used properly

**Comment by jbaxleyiii** [comment]
> This might also enable us to use Xamarin to build Rock.

plz
