### ISSUE TITLE
Check HTML Block on External Workflows on next deploy

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Rock#375]
@dcs619 & @jbaxleyiii We added an HTML Block to the External Workflows. Nothing should happen, but we just want to make sure that on the next deploy to production this block doesn't get overwritten. This is just a placeholder to remember to check that this block still exists after the next deploy.

Thanks gents!

**Comment by briankalwat** [comment]
@richarddubay we good to close this?

**Comment by richarddubay** [comment]
@briankalwat Good gravy...I hope so. 💯
