### ISSUE TITLE
Rock modal theme bug

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock#59]
@jbaxleyiii  @jonhorton  Not sure if this happened with the latest update from Spark (I doubt it because I didn't recompile our theme) 

![screenshot 2015-11-05 10 39 59](https://cloud.githubusercontent.com/assets/1210933/10973005/af78e650-83a9-11e5-9492-1f7e3380d778.png)

**Comment by FrankGrand** [comment]
Last time I noticed this a few weeks ago, it was happening on beta, but not alpha so I assumed that the  latest code would fix it....guess not

**Comment by jbaxleyiii** [comment]
closed by @edolyne
