### ISSUE TITLE
Workflow theme needs padding for mobile selects

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Rock#64]
On mobile the selects go all the way to the left (no padding-left)

There should be padding left to match the metrics blocks

https://alpha-rock.newspring.cc/dashboards/guestservices

**Comment by dcs619** [comment]
This is a bug in the nav-bar class (from core css) not being applied past 768px.  Ben confirmed by changing the theme.  We'll file a bug there.

**Comment by jbaxleyiii** [comment]
Caused by https://github.com/SparkDevNetwork/Rock/issues/1300
