### ISSUE TITLE
No Picture for Logged in User 

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#651]
There is no profile picture for the person logged in

Current Theme:
![home___rock_rms](https://user-images.githubusercontent.com/24526905/37096470-b741face-21e6-11e8-869b-44d4774bdc4f.png)

Prealpha:
![home___rock_rms](https://user-images.githubusercontent.com/24526905/37096501-cd4bb94a-21e6-11e8-9bfa-6b8d2fcfbc04.png)

**Comment by briankalwat** [comment]
@matthewalanwhite I have no idea why this is doing this, but I don't think it's due to theme changes. I think it's a configuration discrepancy between alpha/beta.
