### ISSUE TITLE
External Workflows

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#652]
Need some clarity on the External Workflows page:

![schedule_a_tour_-_newspring_church](https://user-images.githubusercontent.com/24526905/37096852-f6277de4-21e7-11e8-9586-b4d070621947.png)

A. This links to rock.newspring.cc. On external forms (Baptism, Connect, etc.) a user will not need to go to Rock. Can we change this to newspring.cc or even remove the black sidebar.

B. The header doesn't look clean. The title of the workflow and all details would be in the Workflow Entry Block. What do you think about removing that header, or removing text and making the green bars much smaller.

**Comment by briankalwat** [comment]
@matthewalanwhite what is the link for this page?

**Comment by matthewalanwhite** [comment]
Well it might have been because I went from internal to external. But now it looks beautiful! https://alpha-rock.newspring.cc/Workflows/133
