### ISSUE TITLE
Celebrate! Page is blank.

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#653]
https://alpha-rock.newspring.cc/staff/celebrate

![celebrate____rock_rms](https://user-images.githubusercontent.com/24526905/37097307-10c9a748-21e9-11e8-91cc-048000ba01c1.png)

**Comment by briankalwat** [comment]
@matthewalanwhite this is currently blank on Prod: https://rock.newspring.cc/staff/celebrate Should we remove this page?

**Comment by matthewalanwhite** [comment]
@briankalwat I think that would be best. Currently celebrate on the home page is just metrics. So we will delete that page going forward.
