### ISSUE TITLE
Metrics Blocks Sizing

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#655]
Campus Dashboard: https://alpha-rock.newspring.cc/page/488
![campus_dashboard___rock_rms](https://user-images.githubusercontent.com/24526905/37097753-41229e8a-21ea-11e8-92db-89fd913b41ed.png)

Fuse: https://alpha-rock.newspring.cc/page/489
![fuse_dashboard___rock_rms](https://user-images.githubusercontent.com/24526905/37097865-7d9c62b0-21ea-11e8-9c4f-daaf1f97245e.png)

Guest Services: https://alpha-rock.newspring.cc/page/490
![guest_services_dashboard___rock_rms](https://user-images.githubusercontent.com/24526905/37097924-9d785530-21ea-11e8-947f-a3eaea0b25ff.png)

KidSpring: https://alpha-rock.newspring.cc/page/491
![kidspring_dashboard___rock_rms](https://user-images.githubusercontent.com/24526905/37097965-b5fc177c-21ea-11e8-8132-aa042575685d.png)

Next Steps: https://alpha-rock.newspring.cc/page/492
![next_steps_dashboard___rock_rms](https://user-images.githubusercontent.com/24526905/37098003-c7f72016-21ea-11e8-88b3-9d9b22923d5a.png)

**Comment by briankalwat** [comment]
@matthewalanwhite these are fixed.
