### ISSUE TITLE
Communication Template - Image not showing + Default header too big

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Rock#658]
When I designed a communication to have an image at the top of the email, it came to my inbox with no image there. The header of the default template was way to wide as well. 

**Here is the email in the "Email Editor"**
![screen shot 2018-03-07 at 11 20 34 am](https://user-images.githubusercontent.com/22217299/37104041-ae66499c-21f9-11e8-89aa-3c77cce11d78.png)

**Here is the email I received in my inbox**
![screen shot 2018-03-07 at 11 18 04 am](https://user-images.githubusercontent.com/22217299/37104056-b9eef566-21f9-11e8-9185-61b895e16c7e.png)

This should look like - whatever is created in the Email Editor and shown in the "Preview" should be what is delivered to the inbox.

**Comment by briankalwat** [comment]
@morgansmithh do you know that this works with this template in Production? This seems like it would be an issue with the email template and not with the theme, potentially.

**Comment by morgansmithh** [comment]
@briankalwat I'd say yes, but the templates in production aren't available to test in alpha.

**Comment by briankalwat** [comment]
Is the template in alpha that you mentioned is broken in Prod? Can you test that?
