### ISSUE TITLE
Event Registration

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#660]
It looks like the Event Registration them needs some love. https://alpha-rock.newspring.cc/registration/ANDGauntlet2017Attendee

![and_gauntlet_2017___external_workflows](https://user-images.githubusercontent.com/24526905/37156323-c844ab3c-22b3-11e8-8a15-ade679a73b27.png)

![and_gauntlet_2017___external_workflows](https://user-images.githubusercontent.com/24526905/37156357-dd73f7b0-22b3-11e8-9d6f-86592a537982.png)

Would it possible / easy to apply the workflow theme?

**Comment by briankalwat** [comment]
@matthewalanwhite done! https://alpha-rock.newspring.cc/registration/ANDGauntlet2017Attendee

**Comment by matthewalanwhite** [comment]
@briankalwat This was updated on prealpha, but I'm QA'ing everything in Beta and it didn't update.

https://beta-rock.newspring.cc/registration/ANDGauntlet2017Attendee
