### ISSUE TITLE
Scrolling Seems Sluggish on Mobile.

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#661]
Scrolling on mobile seems very sluggish, not fluid at all. This was tested on iOS in Chrome and Safari.

https://drive.google.com/open?id=13CVZmku0ZJAHYnAJOXJqNjQpaUAD20rr

**Comment by briankalwat** [comment]
@matthewalanwhite give this a shot again when you can - should be fixed (with the exception of the navigation - still working on that).

**Comment by matthewalanwhite** [comment]
Looks much better!
