### ISSUE TITLE
Communication Wizard on Mobile

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#662]
The drop down for the list on the communication wizard, extends off the screen.

https://rock.newspring.cc/Communication

![img_257b06ccaa9a-1](https://user-images.githubusercontent.com/24526905/37157666-6b2ca7e8-22b7-11e8-9b96-68712a42e53f.jpeg)

**Comment by briankalwat** [comment]
@matthewalanwhite 
![image](https://user-images.githubusercontent.com/2465823/37426640-7b22179c-279d-11e8-93ce-68c8eb6d02f2.png)
