### ISSUE TITLE
Add Person to Communication on Mobile

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#663]
When you click add a person for "Select Specific Individuals" in the Communication wizard it looks like this:

![img_d3fab95af075-1](https://user-images.githubusercontent.com/24526905/37157780-a89f7bdc-22b7-11e8-87fd-bedf838c1ebd.jpeg)

https://rock.newspring.cc/Communication

**Comment by briankalwat** [comment]
@matthewalanwhite this seems to be a bug on the core Rock theme as well, but i'll see if I can fix it on ours. http://prealpha.rockrms.com/Communication

**Comment by briankalwat** [comment]
@matthewalanwhite 
![image](https://user-images.githubusercontent.com/2465823/37426515-1a861050-279d-11e8-9928-1d4c7d69d599.png)
