### ISSUE TITLE
Select Yourself on the top toolbar on Mobile

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#664]
From any page, when you select the name of the person logged in you get this:

![img_bef0cb982218-1](https://user-images.githubusercontent.com/24526905/37158158-afc881c8-22b8-11e8-9c92-9e6c146a2783.jpeg)

**Comment by briankalwat** [comment]
@matthewalanwhite 
![image](https://user-images.githubusercontent.com/2465823/37426602-58d269da-279d-11e8-8dfd-f45491143383.png)
