### ISSUE TITLE
Action Menu on Mobile

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#665]
On a profile page, when you select actions you get this:

![img_7e940e5d3442-1](https://user-images.githubusercontent.com/24526905/37158286-040b993c-22b9-11e8-8c7a-c92fb496f56c.jpeg)

**Comment by briankalwat** [comment]
@matthewalanwhite also a bug in the core Rock theme.

**Comment by briankalwat** [comment]
@matthewalanwhite should be fixed.
