### ISSUE TITLE
Footer on Person Field Types are Black

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#672]
The "footer" on the select section of the person field type is black.

![workflow_entry___rock_rms](https://user-images.githubusercontent.com/24526905/37170476-e3282ce2-22d8-11e8-8fce-7653ea781f5b.png)

**Comment by briankalwat** [comment]
@matthewalanwhite 
![image](https://user-images.githubusercontent.com/2465823/37426555-34524e36-279d-11e8-99f2-f260237c2409.png)
