### ISSUE TITLE
Labels on Group Pages

### ISSUE THREAD

**Issue by matthewalanwhite** [NewSpring/Rock#673]
There are several labels on the Volunteer/Attendee and Community/Fuse Groups pages that need to be green.

![volunteer_attendee_groups___rock_rms](https://user-images.githubusercontent.com/24526905/37171755-e78b2bf0-22dc-11e8-8dc8-86e756f46950.png)

**Comment by briankalwat** [comment]
@matthewalanwhite these are not green because they are not actionable buttons that take you to another page. I think it's beneficial for us to reserve the green UI for actionable items.
