### ISSUE TITLE
Running Rock in Docker

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Rock#87]
Though I know very little about the ASPNET runtime, I _think_ we can run Rock in a docker container. Taking a look at [this link](https://hub.docker.com/r/microsoft/aspnet/) and [this](http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx) and even [this](https://github.com/aspnet/Home/tree/dev/samples/1.0.0-rc1-update1/HelloWeb), we may have a chance.

@dcs619 I'll work the schedule to see if we can find some time to work on this.

**Comment by dcs619** [comment]
http://weblogs.asp.net/scottgu/docker-and-microsoft-integrating-docker-with-windows-server-and-microsoft-azure

https://github.com/Microsoft/Virtualization-Documentation
