### ISSUE TITLE
[EN] Switching branches for PR's, merges, etc, fails with .remote directory not empty

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock#88]
This isn't an issue so much as an enhancement that would make it easier to contribute to core.

When I switch to a non-NS branch, it complains about the .remote directory not being empty and existing files would be overwritten.  Perhaps there's a way to init that central_az submodule without using the .remote folder? @jbaxleyiii

**Comment by jbaxleyiii** [comment]
This will be fixed #89. Thanks for the heads up @dcs619

**Comment by dcs619** [comment]
:+1:
